### ISSUE TITLE
📎 SOW: Basic Search Functioning

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#392]
# Summary
UTK would like basic search to work, which includes, text and metadata search, proper ranking, and prescribed facets in the UI.

# Accepted Criteria
- [x] #402 
- [ ] ~~The ranking of search results is in a logical order (most relevant?)~~
- [ ] As a user, I can search a work's text or metadata in the catalog search and the parent work will show in the results
- [ ] As a user, I can search a work's text or metadata in the UV search bar and the text will be highlighted in the UV
- [x] As a user, I can click the 'Browse All' button and it will take me to paginated results with facets available to narrow down results 
- [ ] As a user, I can access and customize my search via the drop down in the search bar to be sorted by relevance, date, and title.

To Do:
  - [x] #425
  - [x] #427
  - [x] #420
  - [x] #424
  - [x] #421
  - [x] #422
  - [x] #423
  - [x] #465 

# Screenshots and Videos

# Testing Instructions

# Notes
- What is the expected behavior for the Browse All button

**Comment by markpbaggett** [comment]
@jillpe this looks good.  For point 1, the fields that should be facetable are in our m3 profile with an `indexing` index value of `facetable` and / or if the value should be combined with another property, should be stated as such in `index_documentation` for example:

``` yaml
  photographer:
    available_on:
      class:
      - GenericWork
      - Image
      - Video
      - Audio
      - Pdf
      - Book
      - CompoundObject
      - Newspaper
    cardinality:
      minimum: 0
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#anyURI
      sources:
      - wikidata
      - naf
      - ulan
    definition:
      default: Enter the name of a person (last, first), family, or organization responsible
        for creating a photographic work.
    display_label:
      default: Photographer
    index_documentation: displayable, searchable, creator facet
    indexing:
    - displayable
    - stored_searchable
```

In the example above, `photographer` should not be a facet, but values of `photographer` should be combined in a `creator` facet field.

If we need to do this a different way, let us know.

Also, for ranking, we mean that values in the metadata record  (rdf properties) should account for hire scores than values that appear in free text within the OCR or an attached file.

For `Browse All`, when a user clicks, they should get paginated results with facets available to narrow down results accordingly. 

For sorting, we'd like by `relevance`, `date`, and `title`.
