### ISSUE TITLE
Create CSR/Implement SSL cert/Ingress for hykuadmin.lib.utk.edu

### ISSUE THREAD

**Issue by aprilrieger** [notch8/utk-hyku#534]
Re-work adjacent, the client decided to go in a different direction after speaking with Rob during a client meeting, so linking previous ticket that was completed with the same-ish work: https://github.com/scientist-softserv/utk-hyku/issues/368

Outline of task needing to be completed:
- [x] Create new csr
```
openssl req -new -newkey rsa:2048 -nodes -keyout hykuadmin_lib_utk_edu.key -out hykuadmin_lib_utk_edu.csr
```
This is the info I filled in:
<img width="1013" alt="Screenshot 2023-08-16 at 16 39 06" src="https://github.com/scientist-softserv/utk-hyku/assets/63515648/81f908b2-3379-403d-a22a-be961b3ceede">

- [x] send to client via the vault (creating a new user account @sci email if needed) and send the csr file as an attachment to mbagget1@utk.edu, get client verification
- [x] Add key and csr to 1Password for team access and storage: https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=7gh4bnco6euq2tsap57cq3vhtq&h=scientist.1password.com
- [x] wait for client to send to IT Dept, may take a week to hear anything
- [x] once we have a new cert for hykuadmin.lib.utk.edu, add cert and key to Rancher by selecting the utk-hyku-production namespace in the r2-besties cluster. Create a new TLS secret Storage > Secrets > Create > TLS Certificate, named: `hykuadmin-tls`, we will need to add this value to the ingress tls secretName section. Add the key and the cert (see screenshot below)
<img width="1496" alt="Screenshot 2023-08-16 at 17 35 53" src="https://github.com/scientist-softserv/utk-hyku/assets/63515648/a07dca62-5fde-4c08-a554-55fabbed978b">

- [x] manually create ingress that uses that domain name (see code snippet below)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: utk-hykuadmin
  namespace: utk-hyku-production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
spec:
  rules:
    - host: hykuadmin.lib.utk.edu
      http:
        paths:
          - backend:
              service:
                name: utk-hyku-production-hyrax
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - hykuadmin.lib.utk.edu
      secretName: hykuadmin-tls
```

- [x] Update values in `ops/production-deploy.tmpl.yaml` file to include the following updates and deploy to production:

```
extraEnvVars: &envVars
  - name: HYKU_ADMIN_HOST
    value: hykuadmin.lib.utk.edu
```

- [x] Verify you can login to the proprietor account at: hykuadmin.lib.utk.edu
- [x] Verify there's an active SSL cert in place at: hykuadmin.lib.utk.edu
- [x] make ssl monitor in Site24x7 

# Acceptance Criteria
- [x] You can navigate to hykuadmin.lib.utk.edu and see the proprietor page
- [x] You can login to the proprietor page and interact with the proprietor page
- [x] There is a valid SSL cert in place and you can see the lock in the browser by the url of the site
- [x] make ssl monitor in Site24x7
